name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"
      
      - name: Set up tdd environment
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Run unit tests
        shell: bash -el {0}
        run: PYTHONPATH=. python test/unit/test_fire_gdp.py
        